/* Generated By:JavaCC: Do not edit this line. PartitionParserDefaultVisitor.java Version 6.1_2 */
package com.netflix.metacat.common.partition.parser;

public class PartitionParserDefaultVisitor implements PartitionParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFILTER node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAND node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOR node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNEVAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEVAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLTE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGTE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEQ node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNEQ node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMATCHES node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLIKE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNUM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSTRING node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVAR node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=449d8c0abd893cbe090860f00a25fca3 (do not edit this line) */
