/*
 * Copyright 2016 Netflix, Inc.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. PartitionParserTreeConstants.java Version 6.1_2 */
package com.netflix.metacat.common.partition.parser;

public interface PartitionParserTreeConstants
{
  public int JJTFILTER = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNEVAL = 4;
  public int JJTEVAL = 5;
  public int JJTGT = 6;
  public int JJTLT = 7;
  public int JJTLTE = 8;
  public int JJTGTE = 9;
  public int JJTEQ = 10;
  public int JJTNEQ = 11;
  public int JJTMATCHES = 12;
  public int JJTLIKE = 13;
  public int JJTNUM = 14;
  public int JJTSTRING = 15;
  public int JJTVAR = 16;


  public String[] jjtNodeName = {
    "FILTER",
    "void",
    "AND",
    "OR",
    "NEVAL",
    "EVAL",
    "GT",
    "LT",
    "LTE",
    "GTE",
    "EQ",
    "NEQ",
    "MATCHES",
    "LIKE",
    "NUM",
    "STRING",
    "VAR",
  };
}
/* JavaCC - OriginalChecksum=39fa5c3d77b7e45b2de2245168f22ad8 (do not edit this line) */
