/*
 * Copyright 2016 Netflix, Inc.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. PartitionParserTreeConstants.java Version 6.1_2 */
package com.netflix.metacat.common.partition.parser;

public interface PartitionParserTreeConstants {
    public int JJTFILTER = 0;
    public int JJTVOID = 1;
    public int JJTAND = 2;
    public int JJTOR = 3;
    public int JJTNOT = 4;
    public int JJTBETWEEN = 5;
    public int JJTIN = 6;
    public int JJTLIKE = 7;
    public int JJTCOMPARE = 8;
    public int JJTGT = 9;
    public int JJTLT = 10;
    public int JJTLTE = 11;
    public int JJTGTE = 12;
    public int JJTEQ = 13;
    public int JJTNEQ = 14;
    public int JJTMATCHES = 15;
    public int JJTNUM = 16;
    public int JJTSTRING = 17;
    public int JJTBOOLEAN = 18;
    public int JJTVAR = 19;

    public String[] jjtNodeName = {
        "FILTER",
        "void",
        "AND",
        "OR",
        "NOT",
        "BETWEEN",
        "IN",
        "LIKE",
        "COMPARE",
        "GT",
        "LT",
        "LTE",
        "GTE",
        "EQ",
        "NEQ",
        "MATCHES",
        "NUM",
        "STRING",
        "BOOLEAN",
        "VAR",
    };
}
/* JavaCC - OriginalChecksum=ce17fea735ca77b457031d6eb6193077 (do not edit this line) */
