/* Generated By:JavaCC: Do not edit this line. PartitionParserVisitor.java Version 6.1_2 */
package com.netflix.metacat.common.partition.parser;

public interface PartitionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTFILTER node, Object data);
  public Object visit(ASTAND node, Object data);
  public Object visit(ASTOR node, Object data);
  public Object visit(ASTNEVAL node, Object data);
  public Object visit(ASTEVAL node, Object data);
  public Object visit(ASTGT node, Object data);
  public Object visit(ASTLT node, Object data);
  public Object visit(ASTLTE node, Object data);
  public Object visit(ASTGTE node, Object data);
  public Object visit(ASTEQ node, Object data);
  public Object visit(ASTNEQ node, Object data);
  public Object visit(ASTMATCHES node, Object data);
  public Object visit(ASTLIKE node, Object data);
  public Object visit(ASTNUM node, Object data);
  public Object visit(ASTSTRING node, Object data);
  public Object visit(ASTVAR node, Object data);
}
/* JavaCC - OriginalChecksum=05c7915a864bf7b60e61bf6f66b57af6 (do not edit this line) */
