/* Generated By:JJTree&JavaCC: Do not edit this line. PartitionParserConstants.java */
package com.netflix.metacat.common.partition.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PartitionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 3;
  /** RegularExpression Id. */
  int NEQUAL = 4;
  /** RegularExpression Id. */
  int GTE = 5;
  /** RegularExpression Id. */
  int GT = 6;
  /** RegularExpression Id. */
  int LTE = 7;
  /** RegularExpression Id. */
  int LT = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int MANTISSA = 15;
  /** RegularExpression Id. */
  int DIGITS = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int MATCHES = 20;
  /** RegularExpression Id. */
  int LIKE = 21;
  /** RegularExpression Id. */
  int VARIABLE = 22;
  /** RegularExpression Id. */
  int CHARS = 23;
  /** RegularExpression Id. */
  int QUOTE = 24;
  /** RegularExpression Id. */
  int SQUOTE = 25;
  /** RegularExpression Id. */
  int ENDQUOTE = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int SENDQUOTE = 28;
  /** RegularExpression Id. */
  int SCHAR = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;
  /** Lexical state. */
  int SSTRING_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EQUAL>",
    "<NEQUAL>",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "<INT>",
    "<DIGIT>",
    "<FLOAT>",
    "<EXPONENT>",
    "<MANTISSA>",
    "<DIGITS>",
    "<AND>",
    "<OR>",
    "\"not\"",
    "\"matches\"",
    "\"like\"",
    "<VARIABLE>",
    "<CHARS>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<SENDQUOTE>",
    "<SCHAR>",
  };

}
