/*
 * Copyright 2016 Netflix, Inc.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. PartitionParserTreeConstants.java Version 6.1_2 */
package com.netflix.metacat.common.server.partition.parser;

public interface PartitionParserTreeConstants
{
  public int JJTFILTER = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNOT = 4;
  public int JJTBETWEEN = 5;
  public int JJTIN = 6;
  public int JJTLIKE = 7;
  public int JJTNULL = 8;
  public int JJTCOMPARE = 9;
  public int JJTGT = 10;
  public int JJTLT = 11;
  public int JJTLTE = 12;
  public int JJTGTE = 13;
  public int JJTEQ = 14;
  public int JJTNEQ = 15;
  public int JJTMATCHES = 16;
  public int JJTNUM = 17;
  public int JJTSTRING = 18;
  public int JJTBOOLEAN = 19;
  public int JJTVAR = 20;


  public String[] jjtNodeName = {
    "FILTER",
    "void",
    "AND",
    "OR",
    "NOT",
    "BETWEEN",
    "IN",
    "LIKE",
    "NULL",
    "COMPARE",
    "GT",
    "LT",
    "LTE",
    "GTE",
    "EQ",
    "NEQ",
    "MATCHES",
    "NUM",
    "STRING",
    "BOOLEAN",
    "VAR",
  };
}
/* JavaCC - OriginalChecksum=a96463cb7122b404fe59a717feec7105 (do not edit this line) */
